### ISSUE TITLE
Penalisierung nur bzgl. vergangener Intervalle

### ISSUE THREAD

**Issue by adibender** [adibender/pam#17]
@fabian-s Ist es in `mgcv` (einfach) möglich Penalisierung nur bezüglich vorangegangener Zeitpunkte durchzuführen? Also z.B. dass Penalisierung des 3 Basis-Koeffizienten (der glatten baseline) nur bezüglich der Koeffizienten 1-2 erfolgt, nicht aber 4?

**Comment by fabian-s** [comment]
huh? kannste das mal bitte in mathe notation aufschreiben? versteh nicht wassde meinst, sorry...

**Comment by adibender** [comment]
ja, sry. Ich komme nochmal darauf zurück und mach dann reopen. Kümmere mich jetzt erstmal um die basics.
