### ISSUE TITLE
handling of data frames with matrix columns

### ISSUE THREAD

**Issue by adibender** [adibender/pam#20]
For more complex data sets (with matrix columns as required to fit cumulative effects), dplyr verbs often don't work 
`Error: Each variable must be a 1d atomic vector or list`

May be worth writing functions that clean the data set, i.e. transform 1d vectors to atomic (e.g. function `clean.ped`) and/or call function after checking for and excluding these elements. 

Another possibility would be to store matrix colums as list and only restore the matrix format before fitting the model and vice versa (`as_clean_ped`, `as_fit_ped`)

**Comment by fabian-s** [comment]
Using list columns seems to me to be the most hadlyeverse-compliant solution. 
or maybe even use `tidyr`'s nested tables?
