### ISSUE TITLE
Bug when status variable already present 

### ISSUE THREAD

**Issue by adibender** [adibender/pam#21]
When `status` variable already present in the data set, problems potentially occur as the 
`split_data` function renames the provided event variable to `status` and both variables will be kept 
in the data set, which later causes problems (especially if actual event variable after other `status` variable): 

```r
df <- data.frame(time=1:5, status=c(0, 0, 1, 1, 1), event=c(0, 0, 1, 1, 0))
split_data(Surv(time, event)~., data=df, id="id")
# -> wrong results 

df <- data.frame(time=1:5, status=c(0, 0, 1, 2, 1), event=c(0, 0, 1, 1, 0))
split_data(Surv(time, event)~., data=df, id="id")
# -> warning and NAs in status variable
```

**Comment by adibender** [comment]
The question is how to best handle this? 

1) Obstain from renaming provided `time` and `status` variables in the formula. Would potentially make programming of other functions more difficult. 
2) Rename/Remoe `time` and `status` variables (potentially with warning) in data frame that are not used in the formula. Somewhat intrusive and puzzling to user
3) Throw error/warning and let user handle the issue

**Comment by fabian-s** [comment]
how about calling them `pam_status` or `.status` or `_STATUS_`  or sth weird like that and throw an error if the reserved name is already present in the data?
