### ISSUE TITLE
Transform data to PE format in case of TDC

### ISSUE THREAD

**Issue by adibender** [adibender/pam#29]
Two standard cases (see also #13): 
- [x] data in long format (`pbc` and `pbcseq` from `survival` package)
- [ ] data in wide format (rearrest data)

**Comment by adibender** [comment]
- There is a solution for case 1 now. See example for `?tdc_split` in 	654902a. 

- I think for case 2 we would only need to provide function that transforms wide data to long format and then proceed with case 1, but difficult to generalize/automate, would need an extra argument that provided sampling times of the TDC. @fabian-s Are there good convenience functions for this transformation in `refund`?

**Comment by fabian-s** [comment]
> @fabian-s Are there good convenience functions for this transformation in refund?

nope...

**Comment by adibender** [comment]
hm, than I'll leave it at that for now. Maybe come back to this later
