### ISSUE TITLE
Output of split_data

### ISSUE THREAD

**Issue by adibender** [adibender/pam#30]
I'm considering cleaning up output of `split_data` function a little bit
- dropping `intmid`, `intlen`, `ped_time` as these are not really used anyway
- `intlen` may be useful for calculation of cumulative hazard for example, but can be reconstructed from 
`tstart` and `tend`

**Comment by fabian-s** [comment]
seconded

**Comment by adibender** [comment]
should we rename the function while we at it? 
`split_data` is kind of specific, maybe `as_ped()` instead. `transform_to_ped` is to long and `transform` is probably used in too many other packages/base.

Also we could keep `split_data` as underlying work-horse, while `as_ped` calls `split_data` if no TDC present or does some additional things if TDC are present...

**Comment by fabian-s** [comment]
`ped` or `as.ped` (for consistency with base's S3 conventions, rather than `as_ped`?) is a good idea. I like this!

**Comment by adibender** [comment]
hm, not sure about `as.ped`, it's consistent with base R but `tidyverse` usually uses `as_*` for everything
