### ISSUE TITLE
Vignettes + examples, dependencies + runtimes

### ISSUE THREAD

**Issue by adibender** [adibender/pam#42]
Is this relevant for us?
http://dirk.eddelbuettel.com/blog/2017/03/22/#suggests_is_not_depends

Some examples, vignettes have long runtimes. Is this a problem when submitting to cran?

**Comment by fabian-s** [comment]
RE dirk's post: 

do we have packages that are used in vignettes but not for unit tests / examples? i guess those could go into "Suggests" if the vignette compilation is made optional, but  i wouldn't know how to make vignettes optional...?
easiest of course to just put everything into imports/depends.


RE long run times:

yes, afraid so.  CRAN policy says: 
>Checking the package should take as little CPU time as possible, as the CRAN check farm is a very limited resource and there are thousands of packages. Long-running tests and vignette code can be made optional for checking, but do ensure that the checks that are left do exercise all the features of the package.
If running a package uses multiple threads/cores it must never use more than two simultaneously: the check farm is a shared resource and will typically be running many checks simultaneously.
Examples should run for no more than a few seconds each: they are intended to exemplify to the would-be user how to use the functions in the package.

could work around this by pre-computing these chunks and loading the results in the vignette like so
```
     ```r, fakeChunk, eval = FALSE``
     # code for doing complicated stuff
     ```
     ```r, reloadResults, echo = FALSE``
     readRDS(system.file("fakeChunkResults.rds"))
     ```
```


Another workaround for both issues: just put ONLY static vignette pdfs/htmls into the CRAN release and leave the `.Rmd `code on Github only, see  https://cran.r-project.org/web/packages/R.rsp/vignettes/R_packages-Static_PDF_and_HTML_vignettes.pdf

**Comment by adibender** [comment]
development moved to https://adibender.github.io/pammtools/, vignettes will be only available online via pkgdown
