### ISSUE TITLE
general data trafo function

### ISSUE THREAD

**Issue by adibender** [adibender/pam#49]
Define a general data transformation function, e.g., `as_ped`, that calls sub-routines `split_data`, 
`split_tdc`, depending on signature/use case

**Comment by adibender** [comment]
@fabian-s Whats the best way to go about this? 
S3 dispatch won't work as both functions take `formula` ojbect as first argument. 
How do I decide within `as_ped` whether to call `split_data` or `split_tdc`?

**Comment by fabian-s** [comment]
... not sure, can you post a code example or some use cases/currently failing tests? 

`UseMethod` does have a second argument that allows to dispatch on other arguments than the first, could that be used?

**Comment by adibender** [comment]
I would like to have something like: 

```r 
as_ped(Surv(time, status)~., veteran, id="id") # internally calls split_data
as_ped(Surv(time, status)~., pbc, pbcseq, id="id") # internally calls split_tdc
```
Althoug on second thought, `split_tdc` is also just a wrapper to `split_data` + some pre-/postprocessing. 
Maybe just define `as_ped <- function(formula, data, data_long=NULL, ...)`
and internally `if(is.null(data_long)) split_data(...) else split_tdc(...)`

**Comment by fabian-s** [comment]
defining `as_ped` without S3 methods and doing a manual `signature` check seems more straightforward

- `data_tdc` would be a more descriptive arg-name than `data_long`, I think?
- what about multiple TDCs in separate `data.frames`? 
- what about adding a TDC to an existing `ped`-object?

**Comment by adibender** [comment]
> data_tdc would be a more descriptive arg-name than data_long, I think?

true, or maybe `tdc_data` or `timedep_df`, `timedep_data`?

> what about multiple TDCs in separate data.frames?

I guess the easiest would be to provide a convenience function that "blends" the data frames and 
returns one `tdc_data` object that can be passed to `as_ped`

> what about adding a TDC to an existing ped-object?

That might be more tricky, especially when resolution is finer than existing `ped` object. 

In general, I think this all goes back to #11 
We need a general function that takes two (or more) data frames and blends them together with respect to the time variables in the two (or more) data frames

**Comment by adibender** [comment]
solved in **`pammtools`**: https://adibender.github.io/pammtools/articles/data-transformation.html
