### ISSUE TITLE
make_newdata warning even if specified time correct

### ISSUE THREAD

**Issue by adibender** [adibender/pam#55]
`make_newdata` warns about start/end points no used for original data, although values contained in original ped data. 

```r 
int_df <- split_data(Surv(time, status)~., data.frame(time=1:2, status=c(0,1)), id="id")
make_newdata(int_df, tend=1)
```

**Comment by fabian-s** [comment]
... in your example, `int_df` actually **doesn't** contain `tend = 1` :smirk: 

still a valid criticism....

**Comment by adibender** [comment]
oops, supposed to be `tend=2`, sry. 
Thx for the fix!
