### ISSUE TITLE
Plot convenience functions

### ISSUE THREAD

**Issue by adibender** [adibender/pam#6]
Need convenience functions for plotting (see also #5)
 - [x] hazard, cumulative hazard, survival functions
 - [x] hazar ratios/relative risks (see `relative argument` in `add_term`
 - [x] smooth effects (1d and 2d): see `gg_smooth` and `gg_tensor` and `gg_re`
 - [x] smooth effects with `by` variables (see also #32 )

**Comment by fabian-s** [comment]
plots of all time varying effects (and specifically the baseline!) should be step functions with steps at t  =`tend`, see
adibender/PAMtutorial#33

**Comment by adibender** [comment]
solved in **`pammtools`** using `add_*` functions in combination with `make_newdata`
