### ISSUE TITLE
conflicts with cluster::pam

### ISSUE THREAD

**Issue by adibender** [adibender/pam#64]
just realised, that the recommended `cluster` package contains function `pam`(Partitioning around medioids), and respective object class and s3 methods. 

Do we care?

**Comment by fabian-s** [comment]
shit.....  should have noticed that sooner. we should rename it, I think. 
name conflicts with recommended packages are not good at all.

**Comment by fabian-s** [comment]
pam --> peam? stephaz (pronounced step-haz)? or even **hotstephaz**, then we could rename the paper : *Here come the `hotstephaz`* !11! :+1:

**Comment by adibender** [comment]
Hm, are talking about package name, function name or object/class name?

**Comment by fabian-s** [comment]
wasn't serious. `stephaz` could be used for all, as could `peam`. `pexam`? `ppex`? 
`apex` would have been nice since apex also means "summit, peak" but  that's already taken...

**Comment by adibender** [comment]
oder `pamm` (piece-wise exponential additive mixed model)? Would also be most consistent with acronym combinations PEM + GAMM

**Comment by fabian-s** [comment]
:+1:

**Comment by adibender** [comment]
hm, sehe gerade es gibt schon ein package `pamm` auf CRAN (power analysis mixed models). 
Das heißt zumindest das package kann man nicht so nennen

**Comment by fabian-s** [comment]
.. `pammper`? :grimacing: .... weil wir unsere user ja so *pamper*n?
